### ISSUE TITLE
[BUG] UI Access is not supported for Desktop AppX processes

### ISSUE THREAD

**Issue by Samuel12321** [microsoft/msix-packaging#486] opened 2021-10-28 09:49 UTC
*Project*
MSIX SDK

**Describe the bug**
Cant use .MSIX packaging for an app that uses UIAccess. This has been tested with both WPF Desktop Bridge and WinUI3 Desktop apps using .Msix. 
When launching the app an error "the request is not supported" pops up, and the app fails to launch.

The following error is observed in event viewer:
`0x80070032: Cannot create the process for package fd6e7c45-f095-4b47-a46a-71657af65eae_1.0.0.0_x64__0dbdf1n3n58kt because UI Access is not supported for Desktop AppX processes. [LaunchProcess]`

**To Reproduce**
Install any .msix app with `UIaccess = True`
Error Occurs

**Expected behavior**
It works

**Platform**
Windows 11 64bit Build: 22489.1000

**Additional context**
This is a major problem as it prevents apps that require `UIaccess = True` from using .MSIX packaging, commonly assistive technologies apps.

**Comment by anarvekar-msft** [comment] 2021-11-04 18:01
Closing this one out because it's a duplicate of https://github.com/microsoft/WindowsAppSDK/issues/1669

**Closed by anarvekar-msft** 2021-11-04 18:01 UTC
Labels: Question, Area-External

**Comment by Samuel12321** [comment] 2021-11-04 21:24
Yes but it is relevant to this repo, and the msix repo is pretty much dead, issues in that repo are never addressed.
