### ISSUE TITLE
App Installer Uri Scheme on Windows 10 LTSC

### ISSUE THREAD

**Issue by ducalai** [microsoft/msix-packaging#327] opened 2020-01-14 17:42 UTC
Is App Installer Uri scheme on Windows 10 LTSC 1809 supported?

I tried to install an UWP application using App Installer. When I click on my App Installer File link nothing happens. How can I activate/support it ?

**Comment by GITNE** [comment] 2020-01-20 13:14
This basically a duplicate of #234

> Windows 10 LTSC 1809

AFAIK, MSIX Core is basically meant for systems without any appx support, so effectively Windows 7 and earlier. Currently, MSIX Core redirects any existing `.appx` file association to `msixmgr` on install (and does not restore it to the original system handler on uninstall). You might want to be extra careful on Windows 8 and later systems.

**Comment by YZahringer** [comment] 2020-03-21 18:42
The [App Installer](https://www.microsoft.com/en-us/p/app-installer/) application is missing in the LTSC version. There is no way to install it on a LTSC edition?

I installed with a workaround the Store and the App Installer on a Windows 10 LTSC 1809, then the `.appinstaller` scheme are detected and the installation/update works correctly.

The only solution I found that works natively is to install the application from Powershell with the command: `Add-AppxPackage -AppInstaller https://server-path/setup.appinstaller`

**Comment by jvintzel** [comment] 2020-05-26 18:25
You can download the Desktop App Installer and license from the Microsoft Store for Business to enable protocol activation on LTSC 1809 and later.  Use Add-AppxProvisionedPackage to install the package and offline license file (you must install the license xml file).  

https://docs.microsoft.com/en-us/powershell/module/dism/add-appxprovisionedpackage?view=win10-ps

**Closed by jvintzel** 2020-05-26 18:25 UTC
Labels: bug
